# other
- platform: time_date
  display_options:
    - 'date_time'

# template sensors
- platform: template
  sensors:
    altandorr_state:
      friendly_name: 'Back door state'
      value_template: '{% if is_state("binary_sensor.altandorr", "on") %}Open{% else %}Closed{% endif %}'
      icon_template: '{% if is_state("binary_sensor.altandorr", "on") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'
    entredorr_state:
      friendly_name: 'Front door state'
      value_template: '{% if is_state("binary_sensor.entredorr", "on") %}Open{% else %}Closed{% endif %}'
      icon_template: '{% if is_state("binary_sensor.entredorr", "on") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'
    door_last_opened:
      friendly_name: 'Front door last opened'
      icon_template: mdi:glassdoor
      value_template: '{{ as_timestamp(states.sensor.front_door_opened.last_changed) | timestamp_custom("%a %H:%M", True) }}'
    porch_last_motion:
      friendly_name: 'Porch last motion'
      icon_template: mdi:walk
      value_template: '{{ as_timestamp(states.sensor.porch_motion.last_changed) | timestamp_custom("%a %H:%M", True) }}'
    back_porch_last_motion:
      friendly_name: 'B.porch last motion'
      icon_template: mdi:walk
      value_template: '{{ as_timestamp(states.sensor.back_porch_motion.last_changed) | timestamp_custom("%a %H:%M", True) }}'
    day_night:
      friendly_name: 'Day/Night'
      value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
    sunset:
      friendly_name: 'Next sunset'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%a %H:%M", True) }}'
      icon_template: mdi:weather-sunset-down
    sunrise:
      friendly_name: 'Next sunrise'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%a %H:%M", True) }}'
      icon_template: mdi:weather-sunset-up

